INSERT INTO POSTS (TITLE, CONTENT, CREATED_AT, VIEWS) VALUES ('MyBatis와 H2 연동', '데이터베이스 연동이 성공했습니다.', CURRENT_TIMESTAMP, 0);
INSERT INTO POSTS (TITLE, CONTENT, CREATED_AT, VIEWS) VALUES ('스프링 부트 프로젝트', 'Vibe Coding 프로젝트를 진행 중입니다.', CURRENT_TIMESTAMP, 0);
INSERT INTO POSTS (TITLE, CONTENT, CREATED_AT, VIEWS) VALUES ('테스트 게시글', '초기 데이터 확인용 게시글입니다.', CURRENT_TIMESTAMP, 0);
